apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cap-token-refresh
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - patch
- apiGroups:
  - cloudcredential.openshift.io
  resources:
  - credentialsrequests
  verbs:
  - list
