---
# defaults file for generate_ignition

###################################################################
# Path to binaries
###################################################################
openshift_install: '/usr/local/bin/openshift-install-4.7.0'
openshift_client: '/usr/local/bin/oc-4.7.0'
kubectl: '/usr/local/bin/kubectl-4.7.0'
kubeconfig: "{{ ansible_env.HOME }}/.kube/config"
filetranspile: '/usr/local/bin/filetranspiler'
fakeroots: 'fakeroots'

pull_secret: '{{ mirror_base }}/pull-secret.txt'

master_schedulable: false
cluster_channel: 'stable'

# Set to true if using a private registry that has custom SSL certificates
private_registry: true

fips: false
ssh_public_key_file: '/{{ ansible_env.HOME }}.ssh/id_ed25519.pub'

master_count: 3
worker_count: 3

fips_enabled: false

# Certificate bundle that will be added to the install-config.yaml
# This generally includes a certificate for the disconnected docker registry
certificate_bundle: '/etc/pki/tls/certs/registry.crt'

# none, vmware, aws, azure, gcp

cluster_network_cidr: '10.128.0.0/14'
cluster_network_prefix: 23
service_network_cidr: '172.30.0.0/16'

network_policy: 'NetworkPolicy'

httpd_document_root: '/var/www/html'

filetranspiler: '/usr/local/bin/filetranspiler'

fake_root_base: '/tmp/fakeroots'

pip_cmd: 'pip3'
pip_args: ''

filetranspiler_pip_requirements:
  - 'file-magic'
filetranspiler_rpm_requirements:
  - 'python3-magic'

# Fully air-gap install??
air_gapped: true

# Supported platforms include
# vmware, aws, gcp, bare_metal, none
platform: 'aws'

infrastructure_id: 'abc123'

###############################################

# RedHat CoreOS Version. Might not match OpenShift Version
# 4.3.8 and 4.4.3 currently available
rhcos_ver: '4.7.13'
# OpenShift Version
# 4.3.21 and 4.4.7 currently available
ocp_ver: '4.7.18'
# RHCOS and OpenShift Architecture
arch: 'x86_64'

ign_version:
  '4.2': '2.1.0'
  '4.3': '2.1.0'
  '4.4': '2.1.0'
  '4.5': '2.2.0'
  '4.6': '3.1.0'
  '4.7': '3.1.0'

kube_ssl_enabled: false

ocp_cluster_publish: 'Internal'
ocp_sdn: 'OpenShiftSDN'

ocp_base_domain: 'example.com'
ocp_cluster_name: 'caas'
ocp_cluster_name_verbose: '{{ ocp_cluster_name }}.{{ ocp_base_domain }}'

ssh_key_file: '{{ ansible_env.HOME }}/.ssh/{{ ocp_cluster_name}}_rsa'

stage_ignition: true
###############################################

###############################################################
# Base directory for all other mirror tasks
################################################################
mirror_base: '/opt/openshift'
mirror_registry: 'registry.caas.cia.ic.gov'
mirror_registry_port: '5000'
mirror_transport: 'https'
ignition_configs: "{{ mirror_base }}/{{ ocp_cluster_name }}"
# This is the secret that will be uploaded to the mirror server
# for use in mirroring images
local_pull_secret: '{{ ansible_env.HOME }}/Downloads/pull-secret.txt'
# This is the same secret as above but located on the mirror server

docker_registry_hostname: 'localhost'

# static or dhcp network mode for installing the cluster
network_mode: dhcp

#This needs to be set to the disk where you are installing RHCOS
disk: 'xvda'

##########################################################################################
#
# AWS Variables
#
##########################################################################################

#rhcos_ami:
#  '4.6.8':  'ami-01d4ce8cb7734d27b'
#  '4.7.0':  'ami-0ccf438713c096327'
#  '4.7.7':  'ami-0ccf438713c096327'
#  '4.7.13': 'ami-0ccf438713c096327'

#ec2_endpoint: 'https://ec2.us-iso-east-1.c2s.ic.gov'
#s3_endpoint: 'https://s3.us-iso-east-1.c2s.ic.gov'
#route53_endpoint: 'https://route53.us-iso-east-1.c2s.ic.gov'
#elb_endpoint: 'https://elasticloadbalancing.us-iso-east-1.c2s.ic.gov'
#aws_ssl_enabled: false

#combine: true

#ec2_key_name: 'Combine'

#vpc_id: 'vpc-'
#subnet_id: 'subnet-'
