---

- name: Get vpc facts
  include_tasks: vpc_facts.yml
  when:
    - not (existing_vpc | bool)

- name: Ensure vpc_id is defined
  fail:
    msg: "vpc_id must be defined"
  when:
    - vpc_id is not defined

- name: Deploy Network Cloudformation stack
  delegate_to: localhost
  amazon.aws.cloudformation:
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default(omit) }}"
    security_token: "{{ ansible_env.AWS_SESSION_TOKEN | default(omit) }}"
    region: "{{ ansible_env.AWS_DEFAULT_REGION | default(omit) }}"
    ec2_url: "{{ cloudformation_endpoint | default(omit) }}"
    validate_certs: "{{ aws_ssl_enabled }}"
    stack_name: "{{ infra_stack_name }}"
    state: present
    disable_rollback: false
    create_timeout: 10
    template: "{{ playbook_dir }}/../cloudformation/c2s/network.yaml"
    template_parameters:
      ClusterName: "{{ ocp_cluster_name }}"
      InfrastructureName: "{{ infrastructure_id }}"
      HostedZoneId: "{{ hosted_zone_id }}"
      HostedZoneName: "{{ ocp_base_domain }}"
      PublicSubnets: "{{ ec2_public_subnets | default(ec2_private_subnets) }}"
      PrivateSubnets: "{{ ec2_private_subnets }}"
      VpcId: "{{ vpc_id }}"
      Publish: "{{ ocp_cluster_publish }}"
      Route53Enabled: "{{ route53_enabled | string | lower }}"
  register: network_stack_outputs
  when:
    - cloudformation_based | bool
