---

- name: Get vpc facts
  include_tasks: vpc_facts.yml
  when:
    - (cloudformation_based | bool) and ( not existing_vpc | bool)

- name: Get infra facts
  include_tasks: infra_facts.yml
  when:
    - (cloudformation_based | bool)

- name: Get security facts
  include_tasks: security_facts.yml
  when:
    - (cloudformation_based | bool)

- name: Get RHCOS AMI ID
  import_role:
    name: generate_ignition
    tasks_from: get_ami_id.yml

- name: Deploy control plane Cloudformation stack
  delegate_to: localhost
  amazon.aws.cloudformation:
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default(omit) }}"
    security_token: "{{ ansible_env.AWS_SESSION_TOKEN | default(omit) }}"
    region: "{{ ansible_env.AWS_DEFAULT_REGION | default(omit) }}"
    ec2_url: "{{ cloudformation_endpoint | default(omit) }}"
    validate_certs: "{{ aws_ssl_enabled | default(omit) }}"
    stack_name: "{{ cp_stack_name }}"
    state: present
    disable_rollback: true
    create_timeout: 10
    template: "../cloudformation/c2s/control_plane.yaml"
    template_parameters:
      #ClusterName: "{{ ocp_cluster_name }}"
      InfrastructureName: "{{ infrastructure_id }}"
      RhcosAmi: "{{ rhcos_ami }}"
      Master0Subnet: "{{ ec2_private_subnets[0] }}"
      Master1Subnet: "{{ ec2_private_subnets[1] }}"
      Master2Subnet: "{{ ec2_private_subnets[2] }}"
      IgnitionLocation: "http://{{ s3_bucket }}.s3.us-iso-east-1.c2s.ic.gov/{{ s3_path }}/master.ign"
      MasterInstanceProfileName: "{{ ec2_instance_profile.master }}"
      MasterSecurityGroupId: "{{ ec2_sg.master.id }}"
      IgnitionVersion: "3.2.0"
  register: master_stack_outputs
  tags:
    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to api internal target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ internal_api_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  tags:
    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to service target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ internal_service_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  tags:
    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to api external target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ external_api_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  when:
    (ocp_cluster_publish is match("External"))
  tags:
    - masters
