---

- name: Get vpc facts
  include_tasks: vpc_facts.yml
  when:
    - (cloudformation_based | bool)

- name: Get infra facts
  include_tasks: infra_facts.yml
  when:
    - (cloudformation_based | bool)

- name: Get security facts
  include_tasks: security_facts.yml
  when:
    - (cloudformation_based | bool)

- name: Deploy control plane Cloudformation stack
  delegate_to: localhost
  amazon.aws.cloudformation:
    aws_access_key: "{{ ansible_env.AWS_ACCESS_KEY_ID | default(omit) }}"
    aws_secret_key: "{{ ansible_env.AWS_SECRET_ACCESS_KEY | default(omit) }}"
    security_token: "{{ ansible_env.AWS_SESSION_TOKEN | default(omit) }}"
    region: "{{ ansible_env.AWS_DEFAULT_REGION | default(omit) }}"
    ec2_url: "{{ cloudformation_endpoint | default(omit) }}"
    validate_certs: "{{ aws_ssl_enabled }}"
    stack_name: "{{ cp_stack_name }}"
    state: present
    disable_rollback: true
    create_timeout: 10
    template: "../cloudformation/c2s/control_plane.yaml"
    template_parameters:
      #ClusterName: "{{ ocp_cluster_name }}"
      InfrastructureName: "{{ infrastructure_id }}"
      RhcosAmi: "ami-02c8d3069da232774"
      Master0Subnet: "{{ private_subnets[0].id }}"
      Master1Subnet: "{{ private_subnets[1].id }}"
      Master2Subnet: "{{ private_subnets[2].id }}"
      IgnitionLocation: "https://{{ s3_bucket }}.s3.amazonaws.com/{{ s3_path }}/master.ign"
      #InternalApiTargetGroupArn: "{{ internal_api_target_group_arn }}"
      #InternalServiceTargetGropArn: "{{ internap_service_target_group_arn }}"
      MasterInstanceProfileName: "{{ ec2_instance_profile.master }}"
      MasterSecurityGroupId: "{{ ec2_sg.master.id }}"
      IgnitionVersion: "3.2.0"
      #CertificateAuthorities: ""
  register: master_stack_outputs
  tags:
    - masters

#- name: show master stack output
#  debug:
#    var: master_stack_outputs
#  tags:
#    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to api internal target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ internal_api_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  tags:
    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to service target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ internal_service_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  tags:
    - masters

# Ansible task for this doesn't work correctly in C2S do to some api version error
- name: Add control plane nodes to api external target group
  delegate_to: localhost
  shell: aws --no-verify-ssl elbv2 register-targets --target-group-arn "{{ external_api_target_group_arn }}" --targets '{"Id":"{{ item }}"}'
  loop:
    - "{{ master_stack_outputs.stack_outputs.Master0PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master1PrivateIp }}"
    - "{{ master_stack_outputs.stack_outputs.Master2PrivateIp }}"
  when:
    (ocp_cluster_publish is match("External"))
  tags:
    - masters
