---

- hosts: localhost
  gather_facts: true
  become: false
  tasks:

    - name: Deploy OpenShift4 security groups
      import_role:
        name: deploy_cluster
        tasks_from: deploy_security.yml
