---

- hosts: localhost
  gather_facts: true
  become: false
  tasks:

    - name: Deploy OpenShift4 Control Plane
      import_role:
        name: deploy_cluster
        tasks_from: deploy_control_plane.yml
