AWSTemplateFormatVersion: 2010-09-09
Description: Template for OpenShift Cluster Node Launch (EC2 worker instance)

Parameters:
  InfrastructureName:
    AllowedPattern: ^([a-zA-Z][a-zA-Z0-9\-]{0,26})$
    MaxLength: 27
    MinLength: 1
    ConstraintDescription: >-
      Infrastructure name must be alphanumeric, start with a letter, and have
      a maximum of 27 characters.
    Description: >-
      A short, unique cluster ID used to tag cloud resources and identify items
      owned or used by the cluster. You should use the value generated when
      creating the manifest files using `openshift-install create manifests`.
    Type: String

  RhcosAmi:
    Description: >-
      Current Red Hat Enterprise Linux CoreOS AMI to use for bootstrap.
    Type: AWS::EC2::Image::Id

  Subnet:
    Description: >-
      The subnet to launch the worker node into.
    Type: AWS::EC2::Subnet::Id

  WorkerSecurityGroupId:
    Description: >-
      The master security group ID.
    Type: AWS::EC2::SecurityGroup::Id

  IgnitionLocation:
    Description: >-
      Ignition config file location, such as
      https://api-int.$CLUSTER_NAME.$DOMAIN:22623/config/master
    Type: String

  CertificateAuthorities:
    Description: >-
      Base64 encoded certificate authority string to use, such as
      data:text/plain;charset=utf-8;base64,ABC...xYz==. You should use the
      value generated when creating the ignition config files using
      `openshift-install create ignition-configs`.
    Type: String

  WorkerInstanceProfileName:
    Description: >-
      IAM profile to associate with worker nodes.
    Type: String

  WorkerInstanceType:
    AllowedValues:
      - "m4.xlarge"
      - "m4.2xlarge"
      - "m4.4xlarge"
      - "m4.8xlarge"
      - "m4.10xlarge"
      - "m4.16xlarge"
      - "c4.2xlarge"
      - "c4.4xlarge"
      - "c4.8xlarge"
      - "r4.xlarge"
      - "r4.2xlarge"
      - "r4.4xlarge"
      - "r4.8xlarge"
      - "r4.16xlarge"
      - "m5.xlarge"
      - "m5.2xlarge"
      - "m5.4xlarge"
      - "m5.8xlarge"
      - "m5.10xlarge"
      - "m5.16xlarge"
      - "c5.2xlarge"
      - "c5.4xlarge"
      - "c5.8xlarge"
      - "r5.xlarge"
      - "r5.2xlarge"
      - "r5.4xlarge"
      - "r5.8xlarge"
      - "r5.16xlarge"
    Default: m5.large
    Type: String

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Cluster Information"
        Parameters:
          - InfrastructureName
      - Label:
          default: "Host Information"
        Parameters:
          - WorkerInstanceType
          - RhcosAmi
          - IgnitionLocation
          - CertificateAuthorities
          - WorkerSecurityGroupId
          - WorkerInstanceProfileName
      - Label:
          default: "Network Configuration"
        Parameters:
          - Subnet
    ParameterLabels:
      Subnet:
        default: "Subnet"
      InfrastructureName:
        default: "Infrastructure Name"
      WorkerInstanceType:
        default: "Worker Instance Type"
      WorkerInstanceProfileName:
        default: "Worker Instance Profile Name"
      RhcosAmi:
        default: "Red Hat Enterprise Linux CoreOS AMI ID"
      IgnitionLocation:
        default: "Worker Ignition Source"
      CertificateAuthorities:
        default: "Ignition CA String"
      WorkerSecurityGroupId:
        default: "Worker Security Group ID"

Resources:
  Worker:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref RhcosAmi
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: "120"
            VolumeType: "gp2"
      IamInstanceProfile: !Ref WorkerInstanceProfileName
      InstanceType: !Ref WorkerInstanceType
      NetworkInterfaces:
        - AssociatePublicIpAddress: "false"
          DeviceIndex: "0"
          GroupSet:
            - !Ref "WorkerSecurityGroupId"
          SubnetId: !Ref "Subnet"
      UserData:
        Fn::Base64: !Sub [
          '{"ignition":{"config":{"append":[{"source":"${Source}","verification":{}}]},"security":{"tls":{"certificateAuthorities":[{"source":"${CaBundle}","verification":{}}]}},"timeouts":{},"version":"3.1.0"},"networkd":{},"passwd":{},"storage":{},"systemd":{}}',
          {
            Source: !Ref IgnitionLocation,
            CaBundle: !Ref CertificateAuthorities
          }
        ]
      Tags:
        - Key: Name
          Value: !Join ["-", [!Ref InfrastructureName, "worker"]]
        - Key: !Join ["", ["kubernetes.io/cluster/", !Ref InfrastructureName]]
          Value: "owned"

Outputs:
  PrivateIP:
    Description: The compute node private IP address.
    Value: !GetAtt Worker.PrivateIp
